.TH propwatch 1 "(c) 1997-2003 Gerd Knorr"
.SH NAME
propwatch - a tool to monitor X11 properties
.SH SYNOPSIS
.B propwatch [ options ] property-name ...
.SH DESCRIPTION
.B propwatch
is a tool to monitor window properties of root and application
windows.  Nice for debugging property-based IPC of X11 programs.
.SH OPTIONS
.B propwatch
uses the Athena Widgets and accepts the usual toolkit options like
-display and -geometry.
.P
Additional options are:
.TP
.B -watch display
Display to monitor the windows on.  By default the display specified
in the DISPLAY environment variable or via -display is used, but it is
possible to watch another display instead.
.TP
.B -verbose
be verbose.
.TP
.B -proplog
Log property changes to stdout.
.TP
.B -kbdlog
Log keystrokes to stdout.
.P
All remaining command line arguments are assumed to be property names
which should be monitored.  If no property names are specified, a
build in default (WM_COMMAND) will be used.
.SH ENVIRONMENT
.TP
.B DISPLAY
specifies the display to use for the propwatch window.
.SH SEE ALSO
xprop(1), xhost(1), xauth(1), xwd(1)
.SH AUTHOR
Gerd Knorr <kraxel@bytesex.org>
.SH COPYRIGHT
Copyright (C) 1997-2003 Gerd Knorr
.br
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
