.TH showriff 1 "(c) 1994 UP-Vision Computergrafik, 1998-2000 Gerd Knorr"
.SH NAME
showriff - show structure of RIFF files (wav, avi, ...)
.SH SYNOPSIS
.B showriff [ options ] filename
.SH DESCRIPTION
.B showriff
displays the structure of RIFF files.  Common media files which use
the RIFF format are wave-files and avi-movies.
.SH OPTIONS
.TP
.B -h
display help text
.TP
.B -j
try to decode mjpeg headers
.TP
.B -e
try to continue on errors.
.SH SEE ALSO
c't 11/1994, page 327 ff. (german computer mag)
.SH AUTHOR
Gerd Knorr <kraxel@bytesex.org>
.SH COPYRIGHT
1994 UP-Vision Computergrafik
.br
1998-2000 Gerd Knorr
.P
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
