.TH subtitles 1 "(c) 2000 Gerd Knorr"
.SH NOMBRE
subtitles - muestra subtítulos en xawtv.
.SH SINOPSIS
.B subtitles [ -help | -tty ] <página>
.SH DESCRIPCIÓN
.B subtitles
obtiene la página especificada del teletexto mediante la utilidad alevt-cap
y la muestra por medio de xawtv-remote en un bucle sin fin.  Es sobre todo
útil para páginas que incorporan subtítulos para el programa de TV que
se emite.
Es la página 150 en alemania (y la 888 en españa).
.SH OPCIONES
.TP
.B -help
muestra un breve mensaje de ayuda.
.TP
.B -tty
vuelca una copia de la página del teletexto a la tty.
.SH VEA TAMBIÉN
xawtv(1), xawtv-remote(1), alevt-cap(1)
.SH TRADUCCIÓN
Página traducida al español por Ricardo Villalba <rvm@escomposlinux.org>
